### ISSUE TITLE
wrong name for RULE_TYPE_END_RULE_IF_VARIABLE_LARGER

### ISSUE THREAD

**Issue by farmboy0** [santiontanon/castlemaster2-disassembly#3]
```
Lba49:
            cp RULE_TYPE_END_RULE_IF_VARIABLE_LARGER
            jr nz, Lba53

            ; Rule type 46 (#2e): if variable > value, skip rest of script.
            ld a, e
            cp (hl)
            jr c, Lba5a_next_rule
            jr Lba57_next_rule_skipping

```
This seems wrong:
A (accumulator) := value
N (cp's operand) := variable
cp sets the carry flag when A < N according to https://learn.cemetech.net/index.php?title=Z80:Opcodes:CP
so if value < variable  or variable > value execution continues
so this rule skips execution when variable <= value

Do i miss anything here?

**Comment by santiontanon** [comment]
Ah, true, you are right! I labeled it in reverse! I just fixed this in this commit: https://github.com/santiontanon/castlemaster2-disassembly/commit/bf2961c62b9208d0afd49c337e20e6c0c582d96d

Thanks for reporting!
